#!/usr/bin/env bash
#
# Installation:
#   $ install git-delete-merged-branches /usr/local/bin
#
# Git Alias:
#   $ git config --global --add alias.fp '!git fetch -p && git-delete-merged-branches'
#   $ git config --global --add alias.pp '!git pull -p && git-delete-merged-branches'

git branch --merged | grep -vE '((^\*)|^ *(main|master|develop|development|trunk)$)' | xargs -I % git branch -d %
